#!/bin/bash 

# 获取工程根目录
fadir()  
{  
    local this_dir=`pwd`  
    local child_dir="$1" 
    dirname "$child_dir" 
    cd $this_dir  
} 
CUR_DIR=$(cd `dirname $0` && pwd -P )
  
cd $CUR_DIR

echo "当前文件路径 $CUR_DIR"

read -p "🚀 请输入Pod工程名称: " user_input

pod spec create $user_input




